# db
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password:
  jpa:
      generate-ddl: true
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: create
      properties:
        dialect: org.hibernate.dialect.H2Dialect
#mail
  mail:
    host: smtp.gmail.com
    port: 25
    username: usernamee
    password: password

# app
server.port: 8084